name: 'Dominos Action'
description: 'Orders a ðŸ• from Dominos'
author: 'mattdsteele'
inputs:
  github-token:
    description: 'pass GITHUB_TOKEN here'
  address:
    description: 'Address in comma-separated value. Example: 700 Clark Ave, St. Louis, MO, 63102'
  order-type:
    description: 'Delivery or Carryout'
    default: 'Delivery'
  email:
    description: 'Email address'
  phone:
    description: 'Phone number'
  first-name:
    description: 'First Name'
  last-name:
    description: 'Last Name'
  card-number:
    description: 'CC #'
  expiration:
    description: 'Example: 0115 ;//  01/15 just the numbers "01/15"'
  security-code:
    description: 'CVV number'
  card-postal-code:
    description: 'Postal code for credit card'
  active:
    description: 'Whether to actually order a pizza'
    default: 'false'

runs:
  using: composite
  steps:
    # create an issue in the repo
    - uses: actions/github-script@v6
      env:
        FIRSTNAME: ${{ inputs.first-name }}
        LASTNAME: ${{ inputs.last-name }}
        EMAIL: ${{ inputs.email }}
        PHONE: ${{ inputs.phone }}
      with:
        github-token: ${{ inputs.github-token }}        
        script: |          
          const {FIRSTNAME, LASTNAME, EMAIL, PHONE} = process.env
          github.rest.issues.create({
            repo: context.repo.repo,
            owner: context.repo.owner,
            title: 'ðŸ• time',
            body: `![pizza-drone](https://media.giphy.com/media/HW8qVWQId1aY8/200w_d.gif)
            # Hi @rajbos! A ðŸ• is on its way to ${FIRSTNAME} ${LASTNAME}!

            My pizza algorithm says it should arrive in **35** minutes.
            ** Track the pizza: https://order.dominos.com/orderstorage/GetTrackerData?Phone=${PHONE} **
            > Email receipt sent to ${EMAIL}.

            Please tip the driver appropriately.`
          })




